### ISSUE TITLE
Using fields is broken when running on Linux

### ISSUE THREAD

**Issue by thijsc** [appsignal/mongo-rust-driver#6]
This is working properly on Mac, but on Ubuntu 14.04 64 bit this crash occurs:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555654679 in bson_copy_to ()
(gdb) backtrace
#0  0x0000555555654679 in bson_copy_to ()
#1  0x000055555565e656 in _mongoc_cursor_new ()
#2  0x000055555565af23 in mongoc_collection_find ()
#3  0x000055555561dfb9 in collection::Collection$LT$$u27$a$GT$::find::h450cf8774b67074ebSa ()
#4  0x0000555555592b21 in main::h6b309992319155255Fb ()
#5  0x00005555556a3359 in rust_try_inner ()
#6  0x00005555556a3346 in rust_try ()
#7  0x00005555556a0158 in rt::lang_start::h7f71cff79bf5374c0gx ()
#8  0x00007ffff71f4ec5 in __libc_start_main (main=0x55555559cbb0 <main>, argc=3, argv=0x7fffffffe608, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe5f8) at libc-start.c:287
#9  0x0000555555573ce9 in _start ()
```

Posted about it on the mongo-dev group: https://groups.google.com/forum/#!topic/mongodb-dev/9Y-7wUyr2JM

**Comment by thijsc** [comment]
Fixed in c77cc42024f71f3df6d3705977aeff3972e0b137
